# Generated by Django 3.1.3 on 2020-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtproperty',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
