# Generated by Django 3.1.3 on 2020-12-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitem_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cod'), ('ONLINE', 'Online')], max_length=15),
        ),
    ]
