# Generated by Django 3.1.3 on 2021-01-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201225_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online')], max_length=15),
        ),
    ]
